### PR TITLE
Free art programs setup

### PR DESCRIPTION
**Pull request by SmeckoGeck46**
I thought that perhaps this could use a segment in the Art section dedicated to free art programs. Since I use Krita a lot for digital art lately, I started off with that.

### CODE REVIEW

**Review by BombasticTom — APPROVED** [review]
Good change.

**Review by MemeHovy — APPROVED** [review]
nice change

**Review by ninjamuffin99 — APPROVED** [review]

**Comment by ninjamuffin99** [comment]
nice thanks!!

i need to give krita another go

**Comment by SmeckoGeck46** [comment]
You're welcome.
I'm a bit of a free software fanatic.

**Pull request merged**
