### PR TITLE
fix thingy? (idk if this was intentional)

### PR DESCRIPTION
**Pull request by TyDevX**

### CODE REVIEW

**Comment by TyDevX** [comment]
grahh someone see this already!!

**Comment by BombasticTom** [comment]
The full name of the game is Friday Night Funkin'

**Comment by TyDevX** [comment]
Obviously but that's the only entry in the whole Markdown file that has "FNF'" Instead of "FNF"

**Comment by BombasticTom** [comment]
there's a lot of people doing contributions and most write fnf while others write fnf'

**Comment by TyDevX** [comment]
oh k

**Review by EliteMasterEric — APPROVED** [review]

**Pull request merged**
