### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BombasticTom**
This pull request aims to make the readme file more consistent. I'll list the proposed changes below:
- Moved Week 7 and Base Game FLAs to the art section, because I think that it fits the category better
- Fixed grammar errors, added/improved description for some content.
- Commented out some stuff (because I wasn't sure if they should be kept or not)
- Removed duplicates in Chromatic Scale Guides section

### CODE REVIEW

**Comment by BombasticTom** [comment]
bruh does the linting really check the comments too

**Comment by MarkimusZer0** [comment]
Hi Tom!!!
I'd add back the Week 7 Flas tweet to the resource, a couple of the flas listed in the tweet are actually not in the Funkin' repo (surprisingly), like picoSpeaker's fla for example

**Comment by BombasticTom** [comment]
oh sry didn't know i'll do it right away

**Review by MarkimusZer0 — APPROVED** [review]
Swaggy

**Review by EliteMasterEric — APPROVED** [review]

**Pull request merged**
