### PR TITLE
Add the wiki

### PR DESCRIPTION
**Pull request by upintheairsheep**

### CODE REVIEW

**Comment by EyeDaleHim** [comment]
...Just what is this for, exactly? This barely serves a purpose?

**Comment by upintheairsheep** [comment]
It's for the personalities and facts about the characters, so that mod creators don't make wildly inaccurate versions of the characters, or so they can make tiny references to small facts about them, like their phone preferences.

**Comment by MarkimusZer0** [comment]
Does it really matter that much?????
I mean i don't think people really mind them being not 100% accurate to whatever NM and PA drop which could at any point just be a joke

**Comment by framework212** [comment]
I mean, I'd say the wiki could be a useful resource beyond just character personalities, as there's other stuff about the game documented, plus if something turns out to be a joke it can always be corrected with new information by anyone

**Comment by Burgerballs** [comment]
Ehh i don't believe this needs to be here, mods are made with creative freedom in mind, I believe having some sort of rulebook on how characters should be reperesented goes against that.

**Comment by MarkimusZer0** [comment]
> I mean, I'd say the wiki could be a useful resource beyond just character personalities, as there's other stuff about the game documented, plus if something turns out to be a joke it can always be corrected with new information by anyone

What other stuff do they document i don't really browse wikis much other than on occasion and also sure stuff can be corrected but a lot of the time everything and anything gets taken at face value in these wikis as long as it comes from devs

**Comment by MarkimusZer0** [comment]
"everything and anything"???
This sucks ill smite myself for it later

**Comment by framework212** [comment]
> Ehh i don't believe this needs to be here, mods are made with creative freedom in mind, I believe having some sort of rulebook on how characters should be reperesented goes against that.
The description can be changed; there are other aspects of the wiki that folks may find helpful, and any aspect doesn't only have to be considered with mods in mind.

> What other stuff do they document i don't really browse wikis much other than on occasion and also sure stuff can be corrected but a lot of the time anything and everything gets taken at face value in these wikis as long as it comes from devs
The wiki also documents assets, changes between updates, general information about FNF and its gameplay, details about weeks and songs, character relationships, sprites, official artwork and doodles, and trivia about all of the above. Modders are free to depict the characters how they want, but stuff like personalities, relationships, and trivia may help give an idea of what/how to write stuff with the characters. In terms of the things the devs say, it can be hard to tell what's a joke and what isn't, especially as the devs don't really use tone indicators.

**Comment by EliteMasterEric** [comment]
Please resolve merge conflicts.

**Comment by EliteMasterEric** [comment]
Since this contribution is incredibly stale and the author hasn't pushed any fixes, I'm going to close it.

If anyone still wants this added, they can make a new PR that resolves the issues.

**Pull request closed without merging**
